version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yaml"] # Ensure this matches the filename
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml # Ensure both filenames match exactly
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC endpoint for traces
      - "14268:14268" # HTTP endpoint for traces
      - "6831:6831/udp" # Agent UDP for Thrift compact
      - "6832:6832/udp" # Agent UDP for Thrift binary
